# -*- coding: utf-8 -*-
"""
/***************************************************************************
 
                                 A QGIS plugin
 Accessibility Calculations
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-29
        copyright            : (C) 2023 by Itzhak Benenson
        email                : ibennya@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import os
import site
site.addsitedir(os.path.abspath(os.path.dirname(__file__) + '/cls'))

def classFactory(iface):
    """Load TAUNetCalc class from file TAUNetCalc.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .tau_net_calc import TAUNetCalc
    return TAUNetCalc(iface)
